[build]
  publish = "dist"
  functions = "netlify/functions"

[dev]
  # Use Netlify CLI local dev if available. This will serve functions and static site.
  command = "npm run build:functions && npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
